### ISSUE TITLE
INITIALIZER: list_account_workspaces_to_conf_file - FAILED: Workload failed

### ISSUE THREAD

**Issue by sebolabs** [databricks-industry-solutions/security-analysis-tool#127]
Hi,

I'm getting the following error when running the initializer:

**Source**
```
status1 = dbutils.notebook.run(
    f"{basePath()}/notebooks/Setup/1. list_account_workspaces_to_conf_file", 3000
)
```

**Notebook execution**
```
Py4JJavaError: An error occurred while calling o538.run.
: com.databricks.WorkflowException: com.databricks.NotebookExecutionException: FAILED: Workload failed, see run output for details
	at com.databricks.workflow.WorkflowDriver.run(WorkflowDriver.scala:99)
	at com.databricks.dbutils_v1.impl.NotebookUtilsImpl.run(NotebookUtilsImpl.scala:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:397)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:199)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:119)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.databricks.NotebookExecutionException: FAILED: Workload failed, see run output for details
	at com.databricks.workflow.WorkflowDriver.run0(WorkflowDriver.scala:147)
	at com.databricks.workflow.WorkflowDriver.run(WorkflowDriver.scala:94)
	... 13 more
File <command-3657572880927855>, line 1
----> 1 status1 = dbutils.notebook.run(
      2     f"{basePath()}/notebooks/Setup/1. list_account_workspaces_to_conf_file", 3000
      3 )
      4 if status1 != "OK":
      5     loggr.exception("Error Encountered in Step#1", status1)
File /databricks/python_shell/dbruntime/dbutils.py:221, in DBUtils.NotebookHandler.run(self, path, timeout_seconds, arguments, *args, **kwargs)
    218     __databricks_internal_cluster_spec = kwargs.get(allowed_key, None)
    220 arguments_scala_map = self.sc._jvm.PythonUtils.toScalaMap(arguments)
--> 221 return self.entry_point.getDbutils().notebook().run(
    222     path, timeout_seconds, arguments_scala_map, __databricks_internal_cluster_spec)
File /databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py:1355, in JavaMember.__call__(self, *args)
   1349 command = proto.CALL_COMMAND_NAME +\
   1350     self.command_header +\
   1351     args_command +\
   1352     proto.END_COMMAND_PART
   1354 answer = self.gateway_client.send_command(command)
-> 1355 return_value = get_return_value(
   1356     answer, self.gateway_client, self.target_id, self.name)
   1358 for temp_arg in temp_args:
   1359     if hasattr(temp_arg, "_detach"):
File /databricks/spark/python/pyspark/errors/exceptions/captured.py:224, in capture_sql_exception.<locals>.deco(*a, **kw)
    222 def deco(*a: Any, **kw: Any) -> Any:
    223     try:
--> 224         return f(*a, **kw)
    225     except Py4JJavaError as e:
    226         converted = convert_exception(e.java_exception)
File /databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))
```

**Standard output**
```
Mon Jul 22 08:59:44 2024 Connected to spark.
/databricks/spark/python/pyspark/sql/pandas/conversion.py:413: UserWarning: createDataFrame attempted Arrow optimization because 'spark.sql.execution.arrow.pyspark.enabled' is set to true; however, failed by the reason below:
  Exception thrown when converting pandas.Series (int64) with name 'evaluation_value' to Arrow Array (string).
Direct cause: Expected a string or bytes dtype, got int64
Attempting non-optimization as 'spark.sql.execution.arrow.pyspark.fallback.enabled' is set to true.
  warn(msg)
```

**Log4j output**
```
24/07/22 09:02:50 INFO DataSourceFactory$: DataSource Jdbc URL: jdbc:mariadb://mdv2llxgl8lou0.ceptxxgorjrc.eu-central-1.rds.amazonaws.com:3306/organization1100887946188347?useSSL=true&sslMode=VERIFY_CA&disableSslHostnameVerification=true&trustServerCertificate=false&serverSslCert=/databricks/common/mysql-ssl-ca-cert.crt
24/07/22 09:02:50 INFO HikariDataSource: metastore-monitor - Starting...
24/07/22 09:02:50 INFO HikariDataSource: metastore-monitor - Start completed.
24/07/22 09:02:51 INFO HikariDataSource: metastore-monitor - Shutdown initiated...
24/07/22 09:02:51 INFO HikariDataSource: metastore-monitor - Shutdown completed.
24/07/22 09:02:51 INFO MetastoreMonitor: Metastore healthcheck successful (connection duration = 260 milliseconds)
24/07/22 09:02:54 INFO WorkflowDriver: Workflow run exited with error
com.databricks.NotebookExecutionException: FAILED: Workload failed, see run output for details
	at com.databricks.workflow.WorkflowDriver.run0(WorkflowDriver.scala:147)
	at com.databricks.workflow.WorkflowDriver.run(WorkflowDriver.scala:94)
	at com.databricks.dbutils_v1.impl.NotebookUtilsImpl.run(NotebookUtilsImpl.scala:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:397)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:199)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:119)
	at java.lang.Thread.run(Thread.java:750)
```

Not sure what's wrong.

**Comment by arunpamulapati** [comment]
Please use the diagnostic notebooks under https://github.com/databricks-industry-solutions/security-analysis-tool/tree/main/notebooks/diagnosis to see if the configuration and connectivity are working. If you are still running into issues, please send us an email at sat@databricks.com with a few days and EST-friendly times best for a 30-minute call.

**Comment by arunpamulapati** [comment]
Can you try to run any simple spark read and see if it is working , it it is not working please open support ticker to get some help. 
Here is simple example and let us know if it is working: 

%python

diamonds = spark.read.format('csv').options(header='true', inferSchema='true').load('/databricks-datasets/Rdatasets/data-001/csv/ggplot2/diamonds.csv')

display(diamonds)

**Comment by sebolabs** [comment]
Thanks for your suggestions but I ran out of free tier unfortunately, couldn't get to try it out 😞 
Maybe I'll try another time when I get a new account or someone is willing to pay the bill just so I can do some testing 😉

**Comment by arunpamulapati** [comment]
Thank you. Closing this issue for now.
