### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate on Azure

### ISSUE THREAD

**Issue by ArcTheMaster** [databricks-industry-solutions/security-analysis-tool#174]
The initializer Notebook on Azure is failing after the first steps.

When reaching the part:

```py
status1 = dbutils.notebook.run(
    f"{basePath()}/notebooks/Setup/1. list_account_workspaces_to_conf_file", 3000
)
```

The flow breaks. The specific error happens when `1. list_account_workspaces_to_conf_file` calls `accounts_bootstrap` (see picture below).

![image](https://github.com/user-attachments/assets/5248d377-0a60-4369-a513-2ccd120b1b20)

When checking deeper the underlying error it appears the connection check to the workspace is refused due to a SSL: CERTIFICATE_VERIFY_FAILED error. 

```py
2024-10-31 19:33:51,799 - _profiler_ - INFO - in _update_token_master
2024-10-31 19:33:52,521 - _profiler_ - ERROR - Unsuccessful connection. Verify credentials.
Traceback (most recent call last):
  File "/databricks/python/lib/python3.11/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    self._prepare_proxy(conn)
  File "/databricks/python/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1007, in _prepare_proxy
    conn.connect()
  File "/databricks/python/lib/python3.11/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/databricks/python/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx/providers/Microsoft.Databricks/workspaces?api-version=2018-04-01 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.ipykernel/1836/command-671944820365018-2760754777", line 3, in <module>
    is_successful_acct = db_client.test_connection(master_acct=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/core/dbclient.py", line 150, in test_connection
    results = requests.get(f'{self._url}/subscriptions/{self._subscription_id}/providers/Microsoft.Databricks/workspaces?api-version=2018-04-01',
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx/providers/Microsoft.Databricks/workspaces?api-version=2018-04-01 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))
2024-10-31 19:33:52,524 - _profiler_ - ERROR - HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx/providers/Microsoft.Databricks/workspaces?api-version=2018-04-01 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))
Traceback (most recent call last):
  File "/databricks/python/lib/python3.11/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    self._prepare_proxy(conn)
  File "/databricks/python/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1007, in _prepare_proxy
    conn.connect()
  File "/databricks/python/lib/python3.11/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/databricks/python/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx/providers/Microsoft.Databricks/workspaces?api-version=2018-04-01 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.ipykernel/1836/command-671944820365018-2760754777", line 3, in <module>
    is_successful_acct = db_client.test_connection(master_acct=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/core/dbclient.py", line 150, in test_connection
    results = requests.get(f'{self._url}/subscriptions/{self._subscription_id}/providers/Microsoft.Databricks/workspaces?api-version=2018-04-01',
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx/providers/Microsoft.Databricks/workspaces?api-version=2018-04-01 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))
```

Actually the class `dbclient.test_connection`, or any other class which uses urllib3 get does not support a use of the parameter `verify=False`.

https://github.com/databricks-industry-solutions/security-analysis-tool/blob/61b912254b04590b8c3f26b0f67b76cc3da2ffc1/src/securityanalysistoolproject/core/dbclient.py#L145

The class should give users the choice of turning on or off the SSL certificate verify flag.

**Comment by arunpamulapati** [comment]
Tagging @ramdaskmdb.

**Comment by ramdaskmdb** [comment]
These kind of issues usually occur due to firewall or proxy which adds some self signed or expired certs in the chain. 
Caan you run this from within a cell in your notebook and let us know.

```
%sh
openssl s_client -showcerts -connect management.azure.com:443 
```

**Comment by arunpamulapati** [comment]
Thanks Ram.  @ArcTheMaster You can also use https://github.com/databricks-industry-solutions/security-analysis-tool/blob/main/notebooks/diagnosis/sat_diagnosis_azure.py to test.

**Comment by ArcTheMaster** [comment]
Hi @arunpamulapati @ramdaskmdb ,

Thank you both of you on the replies and the information you shared. 

I added the openssl command inside the sat_diagnosis_azure.py notebook to see if everything works. It passed and this notebook was successful already. At least the main parts because the last commands were returning a SSL error. 

Now no more errors for this diagnosis notebook. Unfortunately the accounts_bootstrap one is still failing.

```py
2024-11-04 13:13:30,909 - _profiler_ - INFO - in _update_token_master
2024-11-04 13:13:31,656 - _profiler_ - INFO - Error. Either the credentials have expired or the                     credentials don't have proper permissions. Re-verify secrets
2024-11-04 13:13:31,657 - _profiler_ - INFO - Forbidden
2024-11-04 13:13:31,657 - _profiler_ - INFO - <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta type="copyright" content="Copyright (C) 1996-2021 The Squid Software Foundation and contributors">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>
<style type="text/css"><!--
 /*
 * Copyright (C) 1996-2022 The Squid Software Foundation and contributors
 *
 * Squid software is distributed under GPLv2+ license and includes
 * contributions from numerous individuals and organizations.
 * Please see the COPYING and CONTRIBUTORS files for details.
 */

/*
 Stylesheet for Squid Error pages
 Adapted from design by Free CSS Templates
 http://www.freecsstemplates.org/
 Released for free under a Creative Commons Attribution 2.5 License
*/

/* Page basics */
* {
	font-family: verdana, sans-serif;
}

html body {
	margin: 0;
	padding: 0;
	background: #efefef;
	font-size: 12px;
	color: #1e1e1e;
}

/* Page displayed title area */
#titles {
	margin-left: 15px;
	padding: 10px;
	padding-left: 100px;
	background: url('/squid-internal-static/icons/SN.png') no-repeat left;
}

/* initial title */
#titles h1 {
	color: #000000;
}
#titles h2 {
	color: #000000;
}

/* special event: FTP success page titles */
#titles ftpsuccess {
	background-color:#00ff00;
	width:100%;
}

/* Page displayed body content area */
#content {
	padding: 10px;
	background: #ffffff;
}

/* General text */
p {
}

/* error brief description */
#error p {
}

/* some data which may have caused the problem */
#data {
}

/* the error message received from the system or other software */
#sysmsg {
}

pre {
}

/* special event: FTP / Gopher directory listing */
#dirmsg {
    font-family: courier, monospace;
    color: black;
    font-size: 10pt;
}
#dirlisting {
    margin-left: 2%;
    margin-right: 2%;
}
#dirlisting tr.entry td.icon,td.filename,td.size,td.date {
    border-bottom: groove;
}
#dirlisting td.size {
    width: 50px;
    text-align: right;
    padding-right: 5px;
}

/* horizontal lines */
hr {
	margin: 0;
}

/* page displayed footer area */
#footer {
	font-size: 9px;
	padding-left: 10px;
}


body
:lang(fa) { direction: rtl; font-size: 100%; font-family: Tahoma, Roya, sans-serif; float: right; }
:lang(he) { direction: rtl; }
 --></style>
</head><body id=ERR_ACCESS_DENIED>
<div id="titles">
<h1>ERROR</h1>
<h2>The requested URL could not be retrieved</h2>
</div>
<hr>

<div id="content">
<p>The following error was encountered while trying to retrieve the URL: <a href="https://management.azure.com/subscriptions/xxxxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxxxxxxx/providers/Microsoft.Databricks/workspaces?">[https://management.azure.com/subscriptions/xxxxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxxxxxxx/providers/Microsoft.Databricks/workspaces?</a></p>](https://management.azure.com/subscriptions/xxxxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxxxxxxx/providers/Microsoft.Databricks/workspaces?%3C/a%3E%3C/p%3E)

<blockquote id="error">
<p><b>Access Denied.</b></p>
</blockquote>

<p>Access control configuration prevents your request from being allowed at this time. Please contact your service provider if you feel this is incorrect.</p>

<p>Your cache administrator is <a href="mailto:webmaster?subject=CacheErrorInfo%20-%20ERR_ACCESS_DENIED&amp;body=CacheHost%3A%2093e9a03bd7bb%0D%0AErrPage%3A%20ERR_ACCESS_DENIED%0D%0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Mon,%2004%20Nov%202024%2013%3A13%3A31%20GMT%0D%0A%0D%0AClientIP%3A%2010.153.204.139%0D%0A%0D%0AHTTP%20Request%3A%0D%0AGET%20%2Fsubscriptions%2Fd70b065a-7699-4216-9ded-2f371a542a0f%2Fproviders%2FMicrosoft.Databricks%2Fworkspaces%3Fapi-version%3D2018-04-01%20HTTP%2F1.1%0AUser-Agent%3A%20databricks-sat%2F0.1.0%0D%0AAccept-Encoding%3A%20gzip,%20deflate%0D%0AAccept%3A%20*%2F*%0D%0AConnection%3A%20keep-alive%0D%0AAuthorization%3A%20Bearer%20eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjNQYUs0RWZ5Qk5RdTNDdGpZc2EzWW1oUTVFMCIsImtpZCI6IjNQYUs0RWZ5Qk5RdTNDdGpZc2EzWW1oUTVFMCJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuYXp1cmUuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZTAxYmQzODYtZmE1MS00MjEwLWEyYTQtMjllNWFiNmY3YWIxLyIsImlhdCI6MTczMDcyNTcxMSwibmJmIjoxNzMwNzI1NzExLCJleHAiOjE3MzA3Mjk2MTEsImFpbyI6ImsyQmdZSkRrbkxpa2Z2dk5qNHNrZGRwTjg2NUdBZ0E9IiwiYXBwaWQiOiI4MzY2ZTMwMi1iOTgxLTQ1N2YtOGQzNy1mZjJhNTM5YWIwNmEiLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9lMDFiZDM4Ni1mYTUxLTQyMTAtYTJhNC0yOWU1YWI2ZjdhYjEvIiwiaWR0eXAiOiJhcHAiLCJvaWQiOiI2MGEyY2IwYi04ZGQxLTQwMWMtYTM1OS03Mzg4OTk1NmFjODEiLCJyaCI6IjEuQVEwQWh0TWI0Rkg2RUVLaXBDbmxxMjk2c1VaSWYza0F1dGRQdWtQYXdmajJNQk1OQUFBTkFBLiIsInN1YiI6IjYwYTJjYjBiLThkZDEtNDAxYy1hMzU5LTczODg5OTU2YWM4MSIsInRpZCI6ImUwMWJkMzg2LWZhNTEtNDIxMC1hMmE0LTI5ZTVhYjZmN2FiMSIsInV0aSI6Im1VQktsbmdnaUV5bURxNFpFNXdzQUEiLCJ2ZXIiOiIxLjAiLCJ4bXNfaWRyZWwiOiIzMCA3IiwieG1zX3RjZHQiOjE0NDA5NDk4NzJ9.QfUt7V6SHxrYBsgY5wiVxMbuM8woZ5Av93OkYVAKmmnwhT4v6xJJxDkA4JMH35bXLgPyINWkwcYToNgIrSfyRHsMUpywbBUD1ADsBPjl1lNhvakyruCl_mn3BfamUr3HdfjdVn9mRfahX0rnEIRKH5xjFVk3b-XihDrU5NufJ6LhYVld6HnCMoM2V6Zq0LJpfHcFealq3az0T62kCnsW5Ic3K7YtpKDEbPNDK2mgtFGPUjsCp0GzW5fgMCXcD15GlHGjtlXUGKym2VbpcbDynOCmhEXzn483y31bY576n8SfzUGZ502x-tCDT4bDIWK42Fw9rgHCK6Di_raV_i1KNA%0D%0AHost%3A%20management.azure.com%0D%0A%0D%0A%0D%0A">webmaster</a>.</p>
<br>
</div>

<hr>
<div id="footer">
<p>Generated Mon, 04 Nov 2024 13:13:31 GMT by 93e9a03bd7bb (squid/5.7)</p>
<!-- ERR_ACCESS_DENIED -->
</div>
</body></html>

2024-11-04 13:13:31,658 - _profiler_ - ERROR - Exception encountered
Traceback (most recent call last):
  File "/root/.ipykernel/1959/command-9139779880878-1615707143", line 4, in <module>
    is_successful_acct = db_client.check_connection(master_acct=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ipykernel/1959/command-9139779881055-3150357518", line 39, in check_connection
    raise Exception(f'Test connection failed {results.reason}')
Exception: Test connection failed Forbidden
```

The credentials are the same as the one used with the diagnosis notebook so it must work. Do you have any ideas ?

**Comment by ramdaskmdb** [comment]
Sounds like your service principal may not have access to the management
api/accounts api. based on this.

<div id="content">
<p>The following error was encountered while trying to retrieve the
URL: <a href="https://management.azure.com/subscriptions/xxxxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxxxxxxx/providers/Microsoft.Databricks/workspaces?">[https://management.azure.com/subscriptions/xxxxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxxxxxxx/providers/Microsoft.Databricks/workspaces?</a></p>](https://management.azure.com/subscriptions/xxxxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxxxxxxx/providers/Microsoft.Databricks/workspaces?%3C/a%3E%3C/p%3E)

<blockquote id="error">
<p><b>Access Denied.</b></p>
</blockquote>

<p>Access control configuration prevents your request from being
allowed at this time. Please contact your service provider if you feel
this is incorrect.</p>


*___________________________________*
*Ramdas Murali*
Solutions Architect -
214.235.8353    |    ***@***.***

**Comment by ArcTheMaster** [comment]
@ramdaskmdb the error does not make sense as the access works during the sat_diagnosis_azure notebook. Credentials are the same. 

Where those permissions need to be aligned ? I tried using a Azure IAM custom role which gives read permissions to the Microsoft.Databricks provider but this is not solving the issue. 

![image](https://github.com/user-attachments/assets/dfa6492f-0081-4157-ad9d-2667d8f4cf40)

Do you know where I need to adjust the permissions more specifically ?

**Comment by arunpamulapati** [comment]
A call may be better. Can you share few times and days best for you that are EST friendly and send an email to ram (ramdas.murali@databricks.com )  and I (arun@databricks.com).

**Comment by ramdaskmdb** [comment]
Hi, can you click on this in your UC and tell us what you see?
[image: image.png]


*___________________________________*
*Ramdas Murali*
Solutions Architect -
214.235.8353    |    ***@***.***

**Comment by ArcTheMaster** [comment]
@ramdaskmdb sorry but we don't see the image. Can you post your comment again please ? I cannot take a look at the UC location without the info. Thx.

**Comment by ramdaskmdb** [comment]
![hms](https://github.com/user-attachments/assets/c513bf62-593d-44f7-aa87-4c31a0c8ed60)

**Comment by ArcTheMaster** [comment]
@arunpamulapati @ramdaskmdb I finally got to the full end of the notebook. I modified multiple notebooks for getting these results though, all Azure related. 

As a summary, this default part does not work properly when working on Azure Cloud + AKV secrets:

```py
# COMMAND ----------

import requests
from core import  parser as pars
from core.dbclient import SatDBClient

if cloud_type =='azure': # use client secret
  client_secret = dbutils.secrets.get(json_['master_name_scope'], json_["client_secret_key"])
  json_.update({'token':'dapijedi', 'client_secret': client_secret})
elif (cloud_type =='aws' and json_['use_sp_auth'].lower() == 'true'):  
    client_secret = dbutils.secrets.get(json_['master_name_scope'], json_["client_secret_key"])
    json_.update({'token':'dapijedi', 'client_secret': client_secret})
    mastername =' ' # this will not be present when using SPs
    masterpwd = ' '  # we still need to send empty user/pwd.
    json_.update({'token':'dapijedi', 'mastername':mastername, 'masterpwd':masterpwd})
else: #lets populate master key for accounts api
    mastername = dbutils.secrets.get(json_['master_name_scope'], json_['master_name_key'])
    masterpwd = dbutils.secrets.get(json_['master_pwd_scope'], json_['master_pwd_key'])
    json_.update({'token':'dapijedi', 'mastername':mastername, 'masterpwd':masterpwd})

db_client = SatDBClient(json_)
```

It is used on the following notebooks:
- `3. test_connections.py`
- `5. import_dashboard_template_lakeview.py`
- `5. import_dashboard_template.py`
- `6. configure_alerts_template.py`
- `accounts_bootstrap.py`
- `sat_diagnosis_azure.py`
- `workspace_bootstrap.py`

To finish, I noticed that SAT cannot build up the full dashboard from one workspace, collecting other workspaces info. To be more specific there: workspace 1 hosts a SAT instance, collects workspace 1 data but does not get workspace 2 and workspace 3 info. See error below (wrong creds even with the proper token and creds)

```py
Access token: <myaccesstoken_workspace1.12>
2024-11-08 20:36:08,383 - _profiler_ - ERROR - Unsuccessful https://adb-1.12.azuredatabricks.net/ 1.12 workspace connection. Verify credentials.
Traceback (most recent call last):
  File "/databricks/python/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/databricks/python/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/databricks/python/lib/python3.11/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/databricks/python/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='adb-1.12.azuredatabricks.net', port=443): Max retries exceeded with url: /api/2.0/clusters/spark-versions (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:992)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.ipykernel/2062/command-3919299609755321-2924787437", line 15, in test_connection
    is_successful_ws = db_client.test_connection(master_acct=accounts_test)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/core/dbclient.py", line 157, in test_connection
    results = requests.get(f'{self._url}/api/2.0/clusters/spark-versions',
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='adb-1.12.azuredatabricks.net', port=443): Max retries exceeded with url: /api/2.0/clusters/spark-versions (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:992)')))
2024-11-08 20:36:08,387 - _profiler_ - INFO - https://adb-1.12.azuredatabricks.net/ workspace connection. Connection Status: False
Access token: <myaccesstoken_workspace2.1>
2024-11-08 20:36:09,503 - _profiler_ - INFO - https://adb-2.1.azuredatabricks.net/ 2.1 : Connection successful!
2024-11-08 20:36:09,504 - _profiler_ - INFO - https://adb-2.1.azuredatabricks.net/ workspace connection. Connection Status: True
[('1.12', False), ('2.1', True)]
```

I will open a new case for this one.

**Comment by ramdaskmdb** [comment]
The hive metastore connection has to work as a pre-requisite. It looks like
port 3306 may be blocked in your case.
Without SAT in the picture, you should be able to click on the
hive_metastore button in UC without any errors.



*___________________________________*
*Ramdas Murali*
Solutions Architect -
214.235.8353    |    ***@***.***

**Comment by ArcTheMaster** [comment]
@ramdaskmdb exact and this is what I shared, once firewalls have been opened it worked. 

But this does not answer my second point about accessing the other workspaces from the SAT instance running on workspace 1. Vnet peering is on between the workspaces so SAT should be able to reach the other workspaces from the same Azure Subscription. Error is either authentication failure or TLS error (same creds are used, token is different though).

**Comment by ramdaskmdb** [comment]
Hi Pierre, This URL does not look right to me.

HTTPSConnectionPool(host='adb-1.12.azuredatabricks.net', port=443)






*___________________________________*
*Ramdas Murali*
Solutions Architect -
214.235.8353    |    ***@***.***

**Comment by ArcTheMaster** [comment]
Hello @ramdaskmdb I anonymized the workspace name on purpose before sending the info in the comment as GitHub is public. The workspace name is perfectly normal in the original stack trace.

**Comment by ArcTheMaster** [comment]
Considering the fact the SSH error comes from a Network path constraint, binded to our own Company context, I close this ticket.
